import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AcaiApp from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Açai +Kisabor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <AcaiApp />
            </body>
        </html>
    );
}
